In [6]:
# Summary: This script demonstrates two tasks. 
# Task 1 replicates NumPy broadcasting using for loops. 
# Task 2 converts a Python dictionary into a NumPy array.

In [7]:
#Task 1: Replicate Broadcasting Using For Loops
import numpy as np

# Set random seed for reproducibility
np.random.seed(123)

# Generate random arrays
x = np.random.randn(4, 4)
y = np.random.randn(4)

# Broadcasting operation
A_broadcast = x / y
print("Result using broadcasting:")
print(A_broadcast)

# Replicating broadcasting with for loops
A_loop = np.zeros_like(x)  # Initialize an empty array with the same shape as x
for i in range(x.shape[0]):  # Loop over rows
    for j in range(x.shape[1]):  # Loop over columns
        A_loop[i, j] = x[i, j] / y[j]  # Perform element-wise division

print("\nResult using for loops:")
print(A_loop)

# Verify that both methods yield the same result
assert np.allclose(A_broadcast, A_loop), "The results do not match!"
print("\nResults match!")

Result using broadcasting:
[[-0.49214189  0.45607819  0.28183596 -3.90043439]
 [-0.26229311  0.75518888 -2.41688145 -1.11063629]
 [ 0.57387869 -0.39635354 -0.67614513 -0.2452416 ]
 [ 0.676082   -0.29216483 -0.44218937 -1.12471925]]

Result using for loops:
[[-0.49214189  0.45607819  0.28183596 -3.90043439]
 [-0.26229311  0.75518888 -2.41688145 -1.11063629]
 [ 0.57387869 -0.39635354 -0.67614513 -0.2452416 ]
 [ 0.676082   -0.29216483 -0.44218937 -1.12471925]]

Results match!


In [8]:
#Task 2: Convert Dictionary to NumPy Array
# Example dictionary
example_dict = {
    "Name": ["Ed", "Edd", "Eddie"],
    "Age": [25, 30, 35],
    "Score": [85.5, 90.0, 88.0]
}

# Convert dictionary values to a NumPy array
dict_array = np.array(list(example_dict.values()))

# Display results
print("\nDictionary:")
print(example_dict)
print("\nConverted NumPy array:")
print(dict_array)

# Optionally, transpose the array for better readability
transposed_array = dict_array.T
print("\nTransposed NumPy array:")
print(transposed_array)


Dictionary:
{'Name': ['Ed', 'Edd', 'Eddie'], 'Age': [25, 30, 35], 'Score': [85.5, 90.0, 88.0]}

Converted NumPy array:
[['Ed' 'Edd' 'Eddie']
 ['25' '30' '35']
 ['85.5' '90.0' '88.0']]

Transposed NumPy array:
[['Ed' '25' '85.5']
 ['Edd' '30' '90.0']
 ['Eddie' '35' '88.0']]
